<a href="https://colab.research.google.com/github/KimiWang6/Pytorch-Learning-from-Website/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- Multi-dimensional matrix containing elements of a single data type
- Work better on GPU's
- float32

In [5]:
import torch
import numpy as np

## Lists

In [1]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [3]:
my_list2 = [1,2,3,4,5]
my_list2
print(type(my_list2))

<class 'list'>


## Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1
print(type(np1))

<class 'numpy.ndarray'>


In [8]:
np1.dtype

dtype('float64')

## Tensors

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.1247,  0.8104, -1.9882,  0.1649],
        [ 0.3010, -0.0963, -0.7356, -1.6414],
        [-0.8010,  0.2337, -1.2641, -1.7082]])

In [11]:
tensor_2d.dtype

torch.float32

In [15]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.4619, 0.1685, 0.8435, 0.7658],
        [0.6842, 0.7772, 0.3184, 0.2623],
        [0.4424, 0.3067, 0.4329, 0.2808]], dtype=torch.float64)